version: '3.9'
services:
  postgres-shard0:
    image: postgres:16
    environment:
      POSTGRES_USER: smartflow
      POSTGRES_PASSWORD: smartflow
      POSTGRES_DB: smartflow
    ports: ["5433:5432"]

  postgres-shard1:
    image: postgres:16
    environment:
      POSTGRES_USER: smartflow
      POSTGRES_PASSWORD: smartflow
      POSTGRES_DB: smartflow
    ports: ["5434:5432"]

  redis:
    image: redis:7
    ports: ["6379:6379"]

  app:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://smartflow:smartflow@postgres-shard0:5432/smartflow
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: super-secret
    volumes:
      - ./:/app
    depends_on: [postgres-shard0, postgres-shard1, redis]
    ports: ["8000:8000"]

  worker:
    build: .
    command: celery -A app.tasks.celery_app.celery_app worker -l info
    environment:
      DATABASE_URL: postgresql+psycopg2://smartflow:smartflow@postgres-shard0:5432/smartflow
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: super-secret
    depends_on: [postgres-shard0, postgres-shard1, redis]

  beat:
    build: .
    command: celery -A app.tasks.celery_app.celery_app beat -l info
    environment:
      DATABASE_URL: postgresql+psycopg2://smartflow:smartflow@postgres-shard0:5432/smartflow
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: super-secret
    depends_on: [postgres-shard0, postgres-shard1, redis]
