apiVersion: apps/v1
kind: Deployment
metadata: { name: smartflow-api }
spec:
  replicas: {{ .Values.fastapi.replicas }}
  selector: { matchLabels: { app: smartflow-api } }
  template:
    metadata: { labels: { app: smartflow-api } }
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports: [{ containerPort: 8000 }]
          envFrom: [{ secretRef: { name: smartflow-secrets } }]
