apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: { name: smartflow-api-policy }
spec:
  podSelector: { matchLabels: { app: smartflow-api } }
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
      - namespaceSelector: {}
  egress:
    - to:
      - podSelector: { matchLabels: { app: redis } }
    - to:
      - podSelector: { matchLabels: { app: postgres-shard0 } }
    - to:
      - podSelector: { matchLabels: { app: postgres-shard1 } }
