apiVersion: v1
kind: Secret
metadata:
  name: smartflow-secrets
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.jwtSecret | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
